from typing import Any, Optional
from google.auth.transport.requests import Request


def build(serviceName: str, version: str, **kwargs: Any) -> 'Resource':
    ...

class Resource:
    def users(self) -> "UsersResource": ...

class UsersResource:
    def threads(self) -> "ThreadsResource": ...
    
    def messages(self) -> "MessagesResource": ...
    
    def labels(self) -> "LabelsResource": ...
    
    def getProfile(self, userId: str) -> Request: ...

class LabelsResource:
    def list(self, userId: str) -> Request: ...

class MessagesResource:
    def list(self, userId: str, maxResults: int, pageToken: Optional[str], q: str) -> Request: ...
    
    def modify(self, userId: str, id: str, body: dict) -> Request: ...
    
class ThreadsResource:
    def list(self, userId: str, maxResults: int, pageToken: Optional[str]) -> Request: ...
    
    def get(self, userId: str, id: str, format: str) -> Request: ...
